### ISSUE TITLE
Is Session.Accept Result Really Compatible With net.Conn?

### ISSUE THREAD

**Issue by kudla** [hashicorp/yamux#114]
Hi
A `Session` instance returns `Stream` one from `Accept` call as a `net.Conn` [here](https://github.com/hashicorp/yamux/blob/master/session.go#L153)

Yet [`net.Conn`](https://pkg.go.dev/net#Conn) among the rest defines
```
	// LocalAddr returns the local network address, if known.
	LocalAddr() Addr

	// RemoteAddr returns the remote network address, if known.
	RemoteAddr() Addr
```
which `Stream` seems like doesn't implement.

So I'm not really sure how this is compiled at all (while it indeed is)?

But my main concern here how can the accepted connection be passed to other consumers which are really supposed to have a pure `net.Conn`?

Should I wrap with some stubs the connections myself? Or are there any intended solution for that?

Thx.

**Comment by hadi77ir** [comment]
Hi,

`Stream` implements `net.Conn` (and its `LocalAddr` and `RemoteAddr` methods, of course). There is no way for a type to partially implement an interface. Those methods are implemented in `addr.go`.

**Comment by kudla** [comment]
Ah, I see. Thank you 👍
