### ISSUE TITLE
Race Condition on Concurrent Reads

### ISSUE THREAD

**Issue by lukaspj** [hashicorp/yamux#139]
Hello!

The docs have recently been updated to state that `Read` can be called concurrently for Streams:
https://github.com/hashicorp/yamux/pull/136

However, I think that this is not the case.

We are using a Goroutine reading an empty byte array to detect remote stream closure like:

```go
  go func() {
    for {
      _, err := stream.Read([]byte{})
      if err != nil {
        cancel()
        _ = stream.SetDeadline(time.Now())
        _ = stream.Close()
        break
      }
    }
  }()
```
We see this read and our primary read going into a deadlock because if the remote closes then this empty read will first run `s.stateLock.Lock()`:
https://github.com/hashicorp/yamux/blob/master/stream.go#L102

And then `s.recvLock.Lock()`:
https://github.com/hashicorp/yamux/blob/master/stream.go#L109

But the other Read is in the midst of sendWindowUpdate:
https://github.com/hashicorp/yamux/blob/master/stream.go#L134

So it has called `s.recvLock.Lock()`:
https://github.com/hashicorp/yamux/blob/master/stream.go#L123

Then it went into the `sendFlags` function:
https://github.com/hashicorp/yamux/blob/master/stream.go#L285

And it is now trying to run `s.stateLock.Lock()`:
https://github.com/hashicorp/yamux/blob/master/stream.go#L255

The difference in order of locking causes stateLock to be locked in thread 1 whereas recvLock is locked in thread 2 and each thread wants both of the locks.

**Comment by tgross** [comment]
Hi @lukaspj! I was the one who made that docs change and you're right that it's not correct. The context of the change was that someone noted that you'd get inconsistent reads when trying to read from a stream from different goroutines, but the `net.Conn` interface in the stdlib (which `Stream` allegedly implements) says you can. I confess I failed to investigate whether it was _actually_ safe to call these method concurrently and only patched the docs to cover not doing what that person reported.

But it's clear that's incorrect. Unfortunately there's no way to express "is safe to use concurrently" in the Go type system, which makes the doc comments on `net.Conn` not strict enough to enforce we're giving you a `net.Conn` that follows those semantics exactly. At this point, it would be a major breaking change for us to do so anyways.

I'm going to re-fix the documentation to make it clear that you should only service a `Stream` from a single goroutine; this is how all the HashiCorp consumers do this already.

All that being said, the process you're using to detect remote stream closure doesn't look safe to me either. As far as I can tell, as soon as you get data on the stream this goroutine is going to spin in a tight loop and chew up a core until the data is read by another goroutine.

**Comment by lukaspj** [comment]
You are absolutely right, that snippet was part of some experimental code.

we ended up improving our code, ensuring only only one thread was reading at a time and using the snippet above without a loop on while writing, which sorted it out on our end
