### ISSUE TITLE
Wrong doc of func (*Session) Accept

### ISSUE THREAD

**Issue by AlexStocks** [hashicorp/yamux#23]
On the [page of yamux](https://godoc.org/github.com/hashicorp/yamux), the words of function Accept and AcceptSteam are as follows:

```
func (s *Session) Accept() (net.Conn, error)
Accept is used to block until the next available stream is ready to be accepted.

func (s *Session) AcceptStream() (*Stream, error)
AcceptStream is used to block until the next available stream is ready to be accepted.
```

Both are the same. Maybe the right illustration of function Accept is:
Accept is used to block until the next available connection is ready to be accepted.

**Comment by evanphx** [comment]
The only difference is that AcceptStream() returns a *Stream, the docs are correct.
