### ISSUE TITLE
YaMUX accept rate slower than I need

### ISSUE THREAD

**Issue by ljackson** [hashicorp/yamux#25]
I have been testing yamux and it does just what I need when looking at 5 to around 100 streams, however the application use case will required 10k or more streams per connection when I simulate this by connecting a client that just openstreams and starts sending as fast as it can on each stream (with an accept backlog of 5k) the accept rate for yamux is painfully slow taking around 3m to accept 10k streams. From what I have profiled it seems the locking interplay between data and accept is painful. Any plans to refactor or perhaps avoid some or all of the locking? I watched your video on the plugin arch and the pain you went through to build yamux so I don't want to have to re-implement myself ;)

Any pointers would be helpful

Thx
Leif

**Comment by armon** [comment]
@ljackson You should profile to see where the bottleneck is. I'm not sure why it would take that long to do the accept if you allow for a huge backlog on both the client and server

**Comment by armon** [comment]
Closing until we get a profile or other debug info.
