### ISSUE TITLE
OpenStream hanging on synCh

### ISSUE THREAD

**Issue by whyrusleeping** [hashicorp/yamux#26]
over on the ipfs project we updated the version of yamux we were using to the latest master from 9feabe6 about a month ago. Since then we started noticing random hanging issues, which i got around to debugging today and it looks like the culprit is the `synCh` channel on the session. Commits that don't contain that logic work just fine, but every commit i've tried with it has hung.

It looks to be an issue with not replacing tokens in the semaphore in all needed cases, maybe a call to `Close` isnt actually releasing a stream the way it should?

Increasing the `AcceptBacklog` in the config 'fixes' the problem, but that just seems like its just buying me more time until it hangs again.

**Comment by armon** [comment]
@whyrusleeping Can you verify that the accept backlog isn't being reached? e.g. it is expected to hang if the backlog is full, but you are saying that it is hanging when the acceptor has not reached the backlog. Do both sides have the same backlog configured (I think that is a potential issue if the two sides disagree).

**Comment by whyrusleeping** [comment]
@armon i'm pretty sure the accept backlog isnt being reached, after reporting the issue i bumped the number up to 8192, which made the issue less likely to occur, but I still encounter it.

I'm reasonably certain that both sides are using the same values for accept backlog. we recently made a breaking change to our network protocol requiring everyone to update to the latest code in order to be on the network, and I still see the hang happening. Here is a stack trace if you are interested:

https://ipfs.io/ipfs/QmUnwtP8rQaVFKdF2gFb2VstiLmySAXByvHG2KzZ4xGqZ6

**Comment by whyrusleeping** [comment]
Any update here? I hit this issue rather frequently

**Comment by whyrusleeping** [comment]
correction to the situation: We're likely hitting the accept backlog limit, but hitting that shouldnt cause it to permanently hang. It should just act like a semaphore and hang until something else completes

**Comment by whyrusleeping** [comment]
I believe i've found the issue. If you open a stream, write to it, then close it fast enough, you can close it before its 'established' thus causing the synCh semaphore to not be released.

Heres a repro:
```go
package main

import (
	"fmt"
	"net"
	"time"

	"github.com/hashicorp/yamux"
)

func tcppipe() (net.Conn, net.Conn) {
	list, err := net.Listen("tcp", "0.0.0.0:0")
	if err != nil {
		panic(err)
	}

	con, err := net.Dial("tcp", list.Addr().String())
	if err != nil {
		panic(err)
	}

	con2, err := list.Accept()
	if err != nil {
		panic(err)
	}

	return con, con2
}

func main() {
	//a, b := net.Pipe()
	a, b := tcppipe() // the slight latency increase of tcp makes the bug more apparent

	cfg_a := &yamux.Config{
		AcceptBacklog:          16,
		ConnectionWriteTimeout: time.Second * 10,
		EnableKeepAlive:        true,
		MaxStreamWindowSize:    256 << 10,
		KeepAliveInterval:      time.Second * 10,
	}

	cfg_b := &yamux.Config{
		AcceptBacklog:          16,
		ConnectionWriteTimeout: time.Second * 10,
		EnableKeepAlive:        true,
		MaxStreamWindowSize:    256 << 10,
		KeepAliveInterval:      time.Second * 10,
	}

	s, err := yamux.Server(a, cfg_a)
	if err != nil {
		panic(err)
	}
	defer s.Close()

	c, err := yamux.Client(b, cfg_b)
	if err != nil {
		panic(err)
	}
	defer c.Close()

	go func() {
		for {
			ns, err := s.OpenStream()
			if err != nil {
				panic(err)
			}
			ns.Close()
			fmt.Println("opened")
		}
	}()

	for {
		ac, err := c.AcceptStream()
		if err != nil {
			panic(err)
		}
		_ = ac
	}
}
```

My current 'patch' is to keep a variable called 'established' on the stream, and if we call closeStream on a stream that belongs to us (id % 2 == session.nextID % 2) and its established field is false, we call establishStream on it to release the token. Its a hack and there is likely a better way to do this that someone more familiar with the codebase can write.

**Comment by armon** [comment]
@whyrusleeping Sorry for the delay, this ticket probably got lost in the noise of issues we get. Tagging @slackpad to investigate this.

**Comment by whyrusleeping** [comment]
@armon awesome, thanks :)
