### ISSUE TITLE
long hang in stream write

### ISSUE THREAD

**Issue by whyrusleeping** [hashicorp/yamux#30]
I finally got around to updating ipfs to use the fixes from #29 and now i'm seeing hangs on the select in  stream.go:199. Its reproducible on the live network, but it takes a little while to happen.

cc @slackpad

**Comment by whyrusleeping** [comment]
not much interesting in the stack trace that i can see, but goroutine 1367200 is the one in question:
https://ipfs.io/ipfs/QmVna5MA35uAvyZtrRfKrvX4RnYPYhe14tw7mtxaKuAvkm

**Comment by whyrusleeping** [comment]
enabling yamux logging on one node, not the node that has the hang, but the node that it should be talking to gives this:
```
2016/05/31 17:05:23 [ERR] yamux: keepalive failed: i/o deadline reached
2016/05/31 17:05:23 [ERR] yamux: Failed to read stream data: read tcp 192.168.0.6:4001->91.7.2.204:54741: use of closed network connection
2016/05/31 17:05:23 [WARN] yamux: failed to send go away: session shutdown
2016/05/31 17:06:38 [ERR] yamux: keepalive failed: i/o deadline reached
2016/05/31 17:06:38 [ERR] yamux: Failed to read header: MAC verification failed
2016/05/31 17:06:38 [ERR] yamux: keepalive failed: i/o deadline reached
2016/05/31 17:08:05 [ERR] yamux: keepalive failed: i/o deadline reached
2016/05/31 17:08:05 [ERR] yamux: Failed to read header: MAC verification failed
2016/05/31 17:13:24 [ERR] yamux: keepalive failed: session shutdown
2016/05/31 17:14:03 [ERR] yamux: keepalive failed: i/o deadline reached
2016/05/31 17:14:04 [ERR] yamux: Failed to read stream data: read tcp 192.168.0.6:4001->187.22.60.84:4001: use of closed network connection
2016/05/31 17:16:42 [ERR] yamux: keepalive failed: i/o deadline reached
2016/05/31 17:16:42 [ERR] yamux: Failed to read stream data: read tcp 192.168.0.6:4001->90.9.46.153:4001: use of closed network connection
2016/05/31 17:16:42 [WARN] yamux: failed to send go away: session shutdown
2016/05/31 17:23:22 [ERR] yamux: keepalive failed: i/o deadline reached
2016/05/31 17:24:58 [ERR] yamux: keepalive failed: i/o deadline reached
```

**Comment by slackpad** [comment]
Hi @whyrusleeping `2016/05/31 17:06:38 [ERR] yamux: Failed to read header: MAC verification failed` is super fishy and makes me think the message framing is getting messed up. Is that always present when you see this?

**Comment by whyrusleeping** [comment]
@slackpad its hard to tell, i can only repro unreliably on our gateway machines that have hundreds of connections. Its difficult to tell if thats correlated or not. I did just start seeing some more of the 'frame for missing stream' messages which seem a bit odd to me.

**Comment by whyrusleeping** [comment]
sometime last night one of our nodes started accumulating a ton of goroutines stuck in `OpenStream`, line 153. Heres a stack trace: http://mars.i.ipfs.team:8080/ipfs/QmNbQh1GUCmAF3e9rL5vz9dAEAUiNV531awmJqXmBqf2ca

**Comment by marco-m** [comment]
@whyrusleeping are these hangs still happening ?

**Comment by whyrusleeping** [comment]
@marco-m They are not, I remember we changed something a while back that fixed it, but can’t remember exactly what it was. @stebalien do you remember?

**Comment by Stebalien** [comment]
No idea. However, we've made quite a few improvements that you might want to take a look at in https://github.com/whyrusleeping/yamux/.

**Comment by marco-m** [comment]
Thanks @whyrusleeping , @Stebalien :-)

**Comment by evanphx** [comment]
Given the age, deployment of yamux, and lack of understanding of the issue I'm going to go ahead and close this.
