### ISSUE TITLE
Option for last stream close to close the session

### ISSUE THREAD

**Issue by AudriusButkevicius** [hashicorp/yamux#36]
I use yamux just for control flow, one stream per connection, and rely on net.Conn interface to communicate.

net.Conn in this case is a yamux.Stream

Any code that relies on net.Conn.Close() to do the right thing, can't really rely on that, as the session and  hence the underlying connection is not closed, so things like closing and reopening a connection do not work.

Usually I end up wrapping yamux.Stream with something that closes the session as you close the stream, but I'd be nice if there was an option in the config to deal with that.

**Comment by evanphx** [comment]
Yamux is designed such that the session always outlives the stream. For your unique case, using a wrapper is best.
