### ISSUE TITLE
Licensing for language port

### ISSUE THREAD

**Issue by nbering** [hashicorp/yamux#49]
In relation to discussion with @mitchellh in hashicorp/go-plugin#27, I'm investigating the possibility of writing a NodeJS implementation of the protocol described in [spec.md](https://github.com/hashicorp/yamux/blob/d1caa6c97c9fc1cc9e83bbe34d0603f9ff0ce8bd/spec.md).

I'm not a licensing expert, but I get the basics. It's my understanding that the MPL applies to the implementation code only, and not necessarily the protocol. However, I'm also aware ports where the developer has access to the source code are in a little bit of a fuzzy area in regards to licensing.

I'd like to publish my port under the MIT License, since this is somewhat customary for the NPM package community, but will maintain the Mozilla Public License for this module if it is the desire of this module's author.

I will provide attribution for the protocol design no matter what license I publish the code under.

Can I publish my port under the MIT License?

**Comment by armon** [comment]
@nbering That is fine, the MPL only covers this specific implementation!
