### ISSUE TITLE
Please consider using Apache2 license instead. 

### ISSUE THREAD

**Issue by c4milo** [hashicorp/yamux#5]
MPL 2.0 requires everybody using this library to disclose source code. Apache2 would encourage more adoption.

**Comment by jbenet** [comment]
@mitchellh  the way the go community + tooling handle vendoring (usually copying source, not statically linking) may impact how the licenses apply.

FWIW, i recently forayed into all these legal questions. After much deliberation, we settled for either 
- (MIT or BSD) + the PATENTS grant file 
- APL2.0
for all our code.

What is the patents grant file?

> WebM, libjingle, libwebrtc, and other chromium parts all bear a PATENTS file
> 
> - http://blog.webmproject.org/2010/06/changes-to-webm-open-source-license.html
> - https://chromium.googlesource.com/webm/libvpx/+/master/PATENTS
> - https://github.com/ReadyTalk/webrtc/blob/master/webrtc/PATENTS
>
> This seems to address the APL 2 / MPL patent grants in a multi-license way. (i.e. a separate patent grant)

It's becoming increasingly common to see MIT/BSD + the PATENTS file, which is _much clearer and straight forward_ than either APL2 or MPL. At this point, the only reason i see for using the MPL is If you really want the code disclosure clause -- i.e. afraid people will keep modified versions of your code private. But do note that this clause makes it likely to be incompatible with many uses, significantly decreasing the reach of your library.

IANAL, TINLA, WTFBBQ
