### ISSUE TITLE
Question about the deadline options...

### ISSUE THREAD

**Issue by svanharmelen** [hashicorp/yamux#6]
Hi @armon, @mitchellh, I was looking at this package in a little more detail and was wondering what the reasoning behind the deadline implementation is? I noticed that when setting a deadline it expects a certain point in time instead of a duration and I fail to understand why it is implemented this way?

Looking at [this](https://github.com/hashicorp/yamux/blob/master/stream.go#L120-L124) part of the code for example, I see that `readDeadline` is checked to see if it has been set and if so the delay is calculated by subtracting the current time from the configured deadline time.

So when I open a new stream and then call `stream.SetDeadline(time.Now().Add(30 * time.Second))` the `readDeadline` would be set to 30 seconds in the future. So if my program starts sending and receiving data within 30 seconds from the time I opened the stream, all should be good right?

But say I communicate using the newly opened stream for about 60 seconds after which some local processing will be done before sending another request over the stream. It will then get to [that same](https://github.com/hashicorp/yamux/blob/master/stream.go#L120-L124) code part again, but this time it will subtract the current time from a time in the past making the duration negative and so `time.After(delay)` will fire immediately giving me a timeout error.

So is it expected and designed to behave this way? Or do I misread/misunderstand how this is meant to be used? I would think that changing the deadlines to durations it could function as a generic timeout which works not only when the stream is opened and is waiting for it's first communication, but also in between communications. Additionally it could be used to make sure streams are cleaned up after not being used for the configured duration (when parallelism or the program layout make it hard to determine when to call `Close()` on the stream safely).

Thanks,

Sander

**Comment by svanharmelen** [comment]
Hmm... Guess I already see why it is done like this as the `net.Conn` interface uses the same approach and has some more detailed comments: http://golang.org/pkg/net/#Conn

So in order to achieve the timeout behaviour I described, I need to keep calling to `SetDeadline()` with updated timestamps after every read/write call. Must admit that this feels a little strange to me, but at least I now know that it's actually meant to be working like this :wink:

**Comment by armon** [comment]
@svanharmelen I agree with you, I think it's annoying, but we needed to match the `net.Conn` interface so that we can use the package transparently
