### ISSUE TITLE
Named connections(routing)

### ISSUE THREAD

**Issue by ilgooz** [hashicorp/yamux#64]
Hi, I've started [Bon](https://github.com/ilgooz/bon) to be able to Open and Accept connections by their route names. With named connections, you can start and handle them like you do with http handlers. This way it is easier to group your connections by their use purposes.
So, please [check out](https://github.com/ilgooz/bon) if you feel like you need them too!

**Comment by AhMyth** [comment]
Bon is simple ,small and really Great library
