### ISSUE TITLE
Missing commit in history

### ISSUE THREAD

**Issue by alvin-huang** [hashicorp/yamux#65]
This is in relation to https://github.com/hashicorp/nomad/issues/4455

I had a look at this today while I was on the hunt for dependency issues in our products.

Turns out the commit in question does exist and `govendor fetch github.com/hashicorp/yamux@2658be15c5f05e76244154714161f17e3e77de2e` works fine: https://github.com/hashicorp/yamux/commit/2658be15c5f05e76244154714161f17e3e77de2e

It came from this PR: (https://github.com/hashicorp/yamux/pull/53) which was merged and has a parent of:
![image](https://user-images.githubusercontent.com/17609145/42478649-7a821866-83a3-11e8-8696-3f5170d97844.png)

However, the trees for master:
![image](https://user-images.githubusercontent.com/17609145/42478946-a2548c38-83a4-11e8-8e1b-7fa89a66094c.png)

vs the tree for: https://github.com/hashicorp/yamux/commits/2658be15c5f05e76244154714161f17e3e77de2e

![image](https://user-images.githubusercontent.com/17609145/42478964-b810a67e-83a4-11e8-8753-ffb52de96f03.png)

is different. Not sure what happened here but `683f491` and `3fc4056` are swapped in the two trees so all the hashes of the commits before them differ. 

Hope this helps but I don't know the code base well enough to do surgery on it so I will leave it to the pros :). Looks like it might just be a rebase error. 

cc: @preetapan @chelseakomlo @mkeeler

**Comment by dgonzalezruiz** [comment]
Could this please get some love?

**Comment by evanphx** [comment]
Given the age, I'm going to go ahead and close this.
